### ISSUE TITLE
problems when I try to load data

### ISSUE THREAD

**Issue by huzhyi21** [MaximeRivest/scimeetr#1]
hi,  I have sucessfully installed the package. 
However, I meet problems when I try to use it.

when I try to read data from txt download from wos: ( I have changed the file to UTF-8)
`wos_df <- import_wos_files(files_directory = fpath)
Warning message:
In readChar(full_file_path, file.info(full_file_path)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale`

**Comment by MaximeRivest** [comment]
The function was improved it should be resolved. Are you able to test it again?
