### ISSUE TITLE
problem when run the demo

### ISSUE THREAD

**Issue by huzhyi21** [MaximeRivest/scimeetr#2]
When I run the demo in `make_scimeetr_visuals` function, problem occured:

processing file: scimeetr.Rmd
  |                                                                 |   1%
  ordinary text without R code

  |.                                                                |   1%
label: unnamed-chunk-1 (with options) 
List of 4
 $ echo   : logi FALSE
 $ warning: logi FALSE
 $ results: chr "hide"
 $ message: logi FALSE

Quitting from lines 29-31 (scimeetr.Rmd) 
Error in evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos,  : 
  unused argument (include_timing = include_timing)

**Comment by MaximeRivest** [comment]
Hi,

Thanks for reporting the issue. I have changed the way we see the results. They are now printed to the console. It should have resolved this bug.
